name: ATAT-CMAKE-Unix Build Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Linux-GCC
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: install-dependencies
      run: sudo apt-get update && sudo apt-get install cmake coinor-libipopt-dev
      
    - name: Build
      run: mkdir build && cmake -Bbuild -H.
    
    - name: Make
      run: cmake --build build/
